name: Pull Request Approved

on:
  pull_request_review:
    types: [submitted]
    branches:
      - feature
    properties:
      reviewState: approved

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find the difference and check pom.xml
        id: modules
        run: |
          # Find the difference between feature and development
          # Fetch only the directory which got change and need to check pom.xml available in that module
          # Store the module names in a variable

      - name: Download Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Loop each module and run Maven clean
        run: |
          for module in "${{ steps.modules.outputs.modules }}"; do
            cd "$module"
            mvn -s /path/to/settings.xml clean
            cd ..
          done

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: development
          force: true
