# This workflow will build a MuleSoft project and deploy to CloudHub

name: Maven build Fetching "settings.xml"

on:
  pull_request:
    types:
    - closed
    - assigned
    - unassigned
    - labeled
    - unlabeled
   
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
    branches:
    - Development
    
    

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Find difference between branches
      id: diff
      run: |
        changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        echo "::set-output name=files::$changed_files"      
    
    - name: Cache Depenedencies
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with maven
      run: mvn -B clean package -s .maven/settings.xml
