# This workflow will build a MuleSoft project and deploy to CloudHub

name: Get changed files in PR

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - raju
env:
  git_token: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files list
      run: |
        sudo apt-get update
        sudo apt-get install jq
        curl -s -H "Authorization: token "${git_token}"" "https://api.github.com/repos/shaiksattarhadi/githubactionslib123/pulls/17/files" >> pr_changed_list.json
        #cat pr_changed_list.json
        changed_list=`jq '.[].filename' pr_changed_list.json`
        cat $changed_list
      
 
